app_first/urls.py
from django.urls import path
from app_first import views

app_name = "app_first"

urlpatterns = [
    path('', views.TopView, name='top'),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path('home/', views.HomeView, name="home"),
    path('download/', views.Dy, name="download"),
    path("ajax-list/",views.Ajax_Append_List, name="ajax-list"),
    path("ajax-left/",views.Ajax_Left_List, name="ajax-left"),
]

idrive/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("app_first.urls")),
]

app_first/models.py
from django.db import models
from django_mysql.models import ListCharField

class data(models.Model):
    username = models.CharField(max_length=50)
    title = ListCharField(
        base_field=models.CharField(max_length=100),
        size = 1000,
        max_length=(101 * 1000),
    )
    play_list = ListCharField(
        base_field=models.CharField(max_length=10000),
        size = 2,
        max_length = (2 * 10001),
    )
    volume = models.IntegerField(default=50)

app_first/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "password"]

app_first/views.py
from django.shortcuts import redirect, render
from app_first import forms
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.views import LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from app_first.models import data
from idrive.settings import STATICFILES_DIRS
import os

def TopView(request):
    form_login = forms.LoginForm()
    form_signin = UserCreationForm()
    ms = ""

    if request.method == 'POST':
        if request.POST['password'] != 'null':
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
                return redirect('/home')
        elif request.POST['password1'] != "null":
            form = UserCreationForm(request.POST)
            if form.is_valid():
                user = form.save()
                login(request, user)
                return redirect('/home')
            for i in User.objects.all():
                if request.POST['username'] == str(i):
                    ms = '※この名前はすでに使われています'

    if request.user.is_authenticated == True:
        return HomeView(request)
    else:
        return render(request, 'app_first/top.html',{'form_login':form_login, 'form_signin':form_signin, 'ms':ms})
def HomeView(request):
    username = str(request.user)
    if data.objects.filter(username = username).exists() == False:
        user_data = data.objects.create(username = username, title=[], play_list = [])
        os.mkdir(STATICFILES_DIRS[0] +"/"+username)
    else:
        user_data = data.objects.get(username = username)
    if request.method == "POST":
        if 'file' in request.FILES:
            names = []
            contents = []
            for f in request.FILES.getlist('file'):
                names.append(f.name)
                contents.append(f.read())
            for i,name in enumerate(names):
                name = name[:-4]
                if not name in user_data.title:
                    user_data.title.append(name)
                    with open(STATICFILES_DIRS[0] +"/"+username+"/"+name+".mp3", "wb") as f:
                        f.write(contents[i])
        elif 'delete_post' in request.POST:
            text = request.POST['st'].split(",")
            delete_name = text[0]
            num = user_data.title.index(delete_name)
            user_data.title.pop(num)
            os.remove(STATICFILES_DIRS[0] +"/"+username+"/"+delete_name+".mp3")

            text.pop(0)
            for i in text:
                if i != "":
                    if len(user_data.play_list[1].split("###")) == 1:
                            user_data.play_list[1] = "null"
                    else:
                        text2 = user_data.play_list[1].split("###")
                        i = int(i)
                        if "$$" in text2[i]:
                            text3 = text2[i].split("$$")
                            text4 = user_data.title[int(num) - 1]
                            text3.remove(text4)
                            text2[i] = "$$".join(text3)
                            user_data.play_list[1] = "###".join(text2)
                        else:
                            text2[i] = "null"
                            user_data.play_list[1] = "###".join(text2)
        elif 'createlist' in request.POST:
            new_list_name = request.POST['list_name']
            if user_data.play_list == []:
                user_data.play_list.append(new_list_name)
                user_data.play_list.append("null")
            else:
                text = user_data.play_list[0]
                if new_list_name not in text.split("$$"):
                    text += '$$' + new_list_name
                    user_data.play_list[0] = text
                    user_data.play_list[1] += "###null"
        elif 'delete_playlist' in request.POST:
            text = request.POST['delete_playlist']
            num = int(text) - 1
            text2 = user_data.play_list
            if len(text2[0].split("$$")) == 1:
                user_data.play_list = ""
            else:
                text3 = text2[0].split("$$")
                text3.pop(num)
                text2[0] = "$$".join(text3)
                text3 = text2[1].split("###")
                text3.pop(num)
                text2[1] = '###'.join(text3)

    user_data.save()

    title = user_data.title
    if user_data.play_list != [] and user_data.play_list != "":
        play_list = user_data.play_list[1]
        pl = (user_data.play_list[0]).split('$$')
    else:
        play_list = ""
        pl = ""
        
    return render(request, 'app_first/Home.html', {'title':title, 'list_names':pl, 'play_list':play_list, 'volume':user_data.volume})

def Dy(request):
    return render(request, 'app_first/Dy.html')

class LogoutView(LoginRequiredMixin, LogoutView):
    template_name = "app_first/top.html"

def Ajax_Append_List(request):
    user_data = data.objects.get(username = request.user)
    text = str(request.POST.get('name_cout')).split('$$')
    text2 = user_data.play_list[1].split("###")
    num = user_data.play_list[0].split('$$').index(text[0])
    if text2[num] == "null":
        text2[num] = text[1]
    else:
        test = text2[num].split("$$")
        jatch = False
        if text[1] in test:
            if test[test.index(text[1])] == test[1]:
                jatch = True
        
        if jatch == False:
            text2[num] += "$$" + text[1]
    text2 = "###".join(text2)
    user_data.play_list[1] = text2

    user_data.save()
    return HomeView(request)

def Ajax_Left_List(request):
    user_data = data.objects.get(username = request.user)
    text = (request.POST.get('song_name')).split("$$")
    if len(user_data.play_list[1].split("###")) == 1:
        user_data.play_list[1] = "null"
    else:
        text2 = user_data.play_list[1].split("###")
        num = int(text[1]) - 1
        if "$$" in text2[num]:
            text3 = text2[num].split("$$")
            text4 = user_data.title[int(text[0]) - 1]
            text3.remove(text4)
            text2[num] = "$$".join(text3)
            user_data.play_list[1] = "###".join(text2)
        else:
            text2[num] = "null"
            user_data.play_list[1] = "###".join(text2)
    user_data.save()
    return HomeView(request)

#'list_dir':os.listdir(STATICFILES_DIRS[0]+"/merg-zh")

app_first/templates/app_first/Dy.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/drawer/3.1.0/css/drawer.min.css">
        <link href="https://fonts.googleapis.com/earlyaccess/nicomoji.css" rel="stylesheet">
        <title>ホーム</title>

        <style>
            .bo{
              margin: 0;
              padding: 0;
              overflow: hidden;
              height:100vh;
            }
            
            iframe {
              border:none;
              width:100%;
              height:100%;
            }
        </style>
    </head>

    <body>
        <nav class="navbar navbar-expand navbar-dark bg-dark">
            <div class="container-fluid">
              <a class="navbar-brand mr-auto hed" href="/" style="font-size:min(3vmax,35px);">Idrive</a>
              <ul class="dropdown">
                <button class="dropdown-toggle btn btn-info float-right hed" data-toggle="dropdown">{{ request.user }}</button>
                    <ul class="dropdown-menu dropdown-menu-right hed">
                      <a href="{% url 'app_first:logout' %}" class="btn btn-light btn-block" style="white-space: nowrap;">ログアウト</a>
                    </ul>
              </ul>
            </div>
        </nav>
    </body>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.0.min.js"integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ="crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/iScroll/5.1.3/iscroll.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/drawer/3.1.0/js/drawer.min.js"></script>
</html>

app_first/templates/app_first/top.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/drawer/3.1.0/css/drawer.min.css">
    <title>ログイン</title>
    <style>
        h1 {
          position: relative;
          color: #158b2b;
          font-size: 9vmin;
          text-align: center;
          margin: 1em 0;
        }
        h1:before {
          content: "";
          position: absolute;
          top: -2.4vmin;
          left: 50%;
          width: 34vmin;
          height: 17vmin;
          border-radius: 50%;
          border: 1.5vmin solid #a6ddb0;
          border-left-color: transparent;
          border-right-color: transparent;
          -webkit-transform: translateX(-50%);
          transform: translateX(-50%);
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Idrive</h1>
            <div id="login_card" class="tab-pane active hed">
                <div class="card mt-3 mx-auto" style="width: 70vmin;font-size: 3vmin;">
                    <div class="card-header">
                        <ul class="nav nav-tabs card-header-tabs" id="menu-list" role="tablist">
                          <li class="nav-item">
                            <a class="nav-link active" href="#login_form" data-bs-toggle="tab">ログイン</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link"  href="#signin_form" data-bs-toggle="tab">サインイン</a>
                          </li>
                        </ul>
                    </div>
                        <div class="card-body">
                            ユーザー名
                            <br>
                            <input style="height: 5vmin;" type="text" class="form-control" id="un">
                            <br>
                            パスワード
                            <br>
                            <input style="height: 5vmin;" type="password" class="form-control" id="pass">
                        </div>
                        <div class="card-footer">
                            <div class="tab-content mt-3">
                                <div class="tab-pane active" id="login_form">
                                    <button style="font-size: 3vmin;" class="btn btn-outline-primary" id="lg">ログイン</button>
                                </div>
                                <div class="tab-pane" id="signin_form">  
                                    <button style="font-size: 3vmin;" class="btn btn-outline-primary" id="si">サインイン</button>
                                </div>
                            </div>
                        </div>
                </div>  
            </div>
        </div>
    </div>

    <form action="" method="POST" id="accept">
        {% csrf_token %}
        <input type="text" name="username" autofocus autocapitalize="none" autocomplete="username" maxlength="150" required id="id_username">
        <input type="password" name="password" autocomplete="current-password" required id="id_password">
        <input type="password" name="password1" autocomplete="new-password" required id="id_password1">
        <input type="password" name="password2" autocomplete="new-password" required id="id_password2">
        <button type="submit" id = "btn">
    </form>

    <script type="text/javascript">
        document.getElementById("accept").style.display = "none";
        document.getElementById("lg").addEventListener('click', function(e){
            document.getElementById("id_username").value=document.getElementById("un").value;
            let pas = document.getElementById("pass").value;
            document.getElementById("id_password").value = pas;
            document.getElementById("id_password1").value = "null";
            document.getElementById("id_password2").value = "null";
            document.getElementById("accept").submit();
        });

        document.getElementById("si").addEventListener('click', function(e){
            document.getElementById("id_username").value=document.getElementById("un").value;
            let pas = document.getElementById("pass").value;
            document.getElementById("id_password1").value = pas;
            document.getElementById("id_password2").value = pas;
            document.getElementById("id_password").value = "null";
            document.getElementById("accept").submit();
        });
    </script>
</body>
<script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>
</html>